### PR TITLE
Run tests against Python 3.7 and add classifier

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by rspeer** [comment]
I'm definitely interested in merging this, as I've noticed that Travis's "3.7-dev" option has stopped working.

How confident are you, though, that this new method of testing on Python 3.7 will keep working? The status of Python 3.7 support seems to keep changing, and this method seems to have no documentation except for people on Travis bug reports saying "try this, it worked for me". In another project, I've decided to just hold off on Python 3.7 testing until Travis supports it out of the box.

**Comment by rspeer** [comment]
I've seen the discussion and I know that Python 3.7 on Trusty isn't supported. What I don't know is what _is_ supported. That is, is this `matrix:` workaround something that Travis actually wants us to use?

Either Travis is sorta-down right now or the `matrix:` configuration is affecting the non-3.7 builds also. The 3.4 machine is failing on this PR, with the following message:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by michael-k** [comment]
I might just be a random failure of the 3.4 job.  It worked here: https://travis-ci.com/michael-k/python-ftfy/builds/84611928

No one from travis ever mentioned how to run tests with Python 3.7 on travis properly.  They never objected to the proposed solution either.  And I have not found any other one so far.

Since the tests are passing on the outdated 3.7-dev (which is 3.7.0a4+), but failing on 3.7.0, I think it's best to go with this solution for now and see if a better solution comes up in the future.  (Moving to xenial completely is no option either since it does not support 3.4.)

The only thing that I don't like about it is the `sudo: true` part since it means running on the old non-container based infrastructure.

**Comment by rspeer** [comment]
If a PR that does nothing but change the Travis configuration is failing its Travis check, and the only explanation is that Travis is super random, am I really supposed to say "oh yeah this is great" and accept it?

Is the "old non-container-based infrastructure" related to the random failures? I would swear I didn't see these failures until attempting to test Python 3.7.

If trying to use these barely-documented features increases the likelihood of build failures, then I'd rather not. I am not trying to be a cutting-edge early adopter of Travis features. I was reluctant to be an adopter of Travis at all, given that we already test ftfy in our internal Jenkins, but some contributors promised it would be easy and unobtrusive. My preference is to leave the Travis configuration as it is, until they come up with a fully-supported way to test 3.4 and 3.7.

I know it's not your fault that Travis is suddenly letting me down, but I'd take the status of the Travis check as evidence that this is the wrong configuration. The right configuration would be one whose test results are not random. If there is no right configuration, I would like to know that.

As a separate topic, at least I'm now aware of the test failure on the released version of 3.7. I'll deal with that as a separate issue.

**Comment by michael-k** [comment]
> If a PR that does nothing but change the Travis configuration is failing its Travis check, and the only explanation is that Travis is super random, am I really supposed to say "oh yeah this is great" and accept it?

No, of course not.  Especially if this PR not only changing the test matrix, but also announce Python 3.7 compatibility in the classifiers (which is obviously not the case).

I only became aware of the incompatibility after opening the PR and seeing the tests fail.  I looked into it, but got lost.  I am not familiar with the code base of ftfy or the unicode implementation in Python.  I never mentioned this of asked for help, because the discussion was only about details of Travis CI's config so far.

My goal is not to advertise adopting any features of Travis CI.  My goal is to ensure Python 3.7 compatibility.  Since you were not aware of Python 3.7 incompatibilities before, but are now and planning to address them, I basically achieved what I came for.

> The right configuration would be one whose test results are not random. If there is no right configuration, I would like to know that.

I have no further knowledge of Travis CI's configuration or internals that the one I already presented.  I'm sorry that I cannot provide additional help.

> I was reluctant to be an adopter of Travis at all, given that we already test ftfy in our internal Jenkins, (…)

The advantage of Travis CI over only having an internal Jenkins is, that the test results are openly visible to everyone without running the tests themselves. But that is not unique to Travis CI.

One of the alternatives I'm aware of is CircleCI.  I'm not especially familiar with it, but I know that they use Docker Images ([repo](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images), [hub](https://hub.docker.com/r/circleci/python/tags/)), support Python 2.7 and 3.4–3.7 and seem able to adopt new stable Python versions quicker.  (Because they do not depend on Ubuntu LTS.)

I do not believe that you're interested in supplementing the CI with CircleCI or replacing Travis CI, but if you are, let me know and I'm happy to provide a configuration.

> My preference is to leave the Travis configuration as it is, until they come up with a fully-supported way to test 3.4 and 3.7.

I'm fine with that and I'm going to close the PR.

Just as a side note:  I don't believe that they'll do so before Python 3.4 reaches its [EOL](https://www.python.org/dev/peps/pep-0429/#release-schedule) in about 6 months.

> As a separate topic, at least I'm now aware of the test failure on the released version of 3.7. I'll deal with that as a separate issue.

As I've said, that's what I'm really interested in and I'm glad to hear it. :+1:

**Comment by rspeer** [comment]
Right, sorry about disregarding the part about the Trove classifier. I'll make sure to add that too.

If Travis continues to be frustrating, I may be interested in looking into Circle CI for public-facing test results. But it seems likely that Travis is at least going to sort out their Ubuntu problems in the next, uh, (looks at Trusty EOL date) 7 months.

**Comment by michael-k** [comment]
> That is, is this `matrix:` workaround something that Travis actually wants us to use? It doesn't seem to be in their documentation, it's just something that random users have recommended.

@rspeer FYI: They “announced” the official way to run tests against Python 3.7: https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905 (the author is a travis employee)

It does not include anything about `matrix`.  I somehow missed before that you were asking about `matrix` specifically, so here is the documentation: https://docs.travis-ci.com/user/customizing-the-build/#build-matrix (general documentation that is; not sure if that's what you were looking for, but I don't know about any other)

Anyway, thanks for fixing the Python 3.7 support. :+1:

**Pull request closed without merging**
